### PR TITLE
Removing files from intermediate dir to prevent old screenshots from reappearing

### PR DESCRIPTION
**Pull request by pedromfmachado**
Proposed solution for #615

### CODE REVIEW

**Comment by takahirom** [comment]
Thanks! We need a test to ensure this type of error is caught. Could you add one that specifically triggers this failure?

**Comment by pedromfmachado** [comment]
I've added the test and confirmed it was triggering the issue before the fix was applied. It also helped me improve the fix to use `test.systemProperties` instead of `roborazziProperties` as the previous solution was only working correctly when the system parameter (`-Proborazzi.test.record=true`) was used.

**Comment by takahirom** [comment]
l'm concerned that this implementation might remove other reference (golden) images when users save images in GitHub and run tests with the --tests className .method option or category filters to update screenshots. It seems like we need a test case to cover this scenario. Do you have time to handle this?

**Comment by pedromfmachado** [comment]
I've added a test to cover the filtering case, it looks like the implementation doesn't cause any problems with that.
I was, however, a bit confused with the reference to `src/screeeshots` in your comment, did you mean that it's also relevant to add two similar tests for the custom output directory use case?

**Comment by takahirom** [comment]
This is quite difficult to handle correctly, and it's very challenging. I've checked several patterns locally, and this appears to work as intended. 
Thank you for your excellent contribution!

**Pull request merged**
