### PR TITLE
Added RoborazziComposeActivityThemeOption

### PR DESCRIPTION
**Pull request by pedromfmachado**
As discussed in #598, this PR introduces `RoborazziComposeActivityThemeOption`, allowing for the customisation of the test activity's theme.

### CODE REVIEW

**Comment by takahirom** [comment]
Before 👀 
image

**Comment by takahirom** [comment]
I'll check why the CI fail 👀

**Comment by pedromfmachado** [comment]
Thanks @takahirom, it helps me get a better grasp of the project!

Added a couple of things that seemed to be missing:
- The manifest declaration of `RoborazziActivity` which was needed by the tests within `ComposeTest`;
- Considering `createActivityScenarioOptions` within the `builder()` method of `RoborazziComposeOptions`.

I hope this fixes the checks. 🙂

**Comment by takahirom** [comment]
Thank you for your contribution!

**Pull request merged**
