### PR TITLE
[WIP]Use DrawListener for NativeGraphics

### PR DESCRIPTION
**Pull request by takahirom**
OnDrawListener seems it does not work now

### CODE REVIEW

**Comment by takahirom** [comment]
copilot:all

**Comment by yschimke** [comment]
I got this when trying to record a compose gif.  Is it related to this?

```
java.lang.IllegalArgumentException: Window doesn't have a backing surface!
	at android.view.PixelCopy.request(PixelCopy.java:270)
	at com.github.takahirom.roborazzi.ViewScreenshotKt.generateBitmapFromPixelCopy(ViewScreenshot.kt:174)
	at com.github.takahirom.roborazzi.ViewScreenshotKt.generateBitmapFromPixelCopy(ViewScreenshot.kt:157)
	at com.github.takahirom.roborazzi.ViewScreenshotKt.generateBitmap(ViewScreenshot.kt:95)
	at com.github.takahirom.roborazzi.ViewScreenshotKt.fetchImage(ViewScreenshot.kt:29)
	at com.github.takahirom.roborazzi.ComposeScreenshotKt.fetchImage(ComposeScreenshot.kt:29)
	at com.github.takahirom.roborazzi.RoboComponent$Compose.<init>(capture.kt:95)
	at com.github.takahirom.roborazzi.RoborazziKt$captureComposeNode$capture$1.invoke(Roborazzi.kt:457)
	at com.github.takahirom.roborazzi.RoborazziKt$captureComposeNode$capture$1.invoke(Roborazzi.kt:455)
	at com.github.takahirom.roborazzi.RoborazziKt$captureComposeNode$2$invoke$$inlined$doOnNextLayout$1.onLayoutChange(View.kt:412)
	at android.view.View.layout(View.java:19604)
	at android.view.ViewGroup.layout(ViewGroup.java:6053)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2484)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2200)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1386)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6733)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)
	at android.view.Choreographer.doCallbacks(Choreographer.java:723)
	at android.view.Choreographer.doFrame(Choreographer.java:658)
```

**Comment by takahirom** [comment]
👀

**Comment by takahirom** [comment]
This PR is an attempt to use the onPreDrawListener to capture changes in Compose, but it's not being called at the moment. I'm not certain if it's related to whether the ViewRootImpl has a surface or not. It might be a good idea to create an issue for that crash.

**Comment by takahirom** [comment]
I found your repository with the issues. I'll take a look and try to help.

**Comment by takahirom** [comment]
@yschimke
I haven't encountered the crash you mentioned. However, I discovered an issue where Compose changes were not being captured. I've resolved the issue and would appreciate it if you could review my changes. The fix might be in this PR.
https://github.com/takahirom/roborazzi/pull/52

**Comment by yschimke** [comment]
Will test against next release, or snapshots if you have some?

**Comment by takahirom** [comment]
The current implementation of Compose has been changed to use Snapshot.registerApplyObserver(), and this may cause a conflict. Therefore, we cannot use the implementation from this PR any longer. As for the ImageView's drawable issue, I will try it in Robolectric's next release. Additionally, we should consider adding some animation samples to check it.

**Pull request closed without merging**
